sector: defense
services:
  control-center-ui:
    dashboard:
      layout:
        grid_size: 12
        max_columns: 4
        max_rows: 6
        responsive: true
        mobile_optimized: false
        parameters:
          tactical_layout: true
          security_clearance: "classified"
      widgets:
        fleet_overview:
          enabled: true
          size: "large"
          position:
            x: 0
            y: 0
            width: 4
            height: 2
          refresh_interval_seconds: 10
          parameters:
            show_mission_status: true
            show_ammunition_status: true
            show_fuel_status: true
        vehicle_status:
          enabled: true
          size: "medium"
          position:
            x: 4
            y: 0
            width: 4
            height: 2
          refresh_interval_seconds: 5
          parameters:
            show_location: true
            show_formation: true
            show_threat_level: true
        task_queue:
          enabled: true
          size: "large"
          position:
            x: 0
            y: 2
            width: 4
            height: 2
          refresh_interval_seconds: 5
          parameters:
            show_mission_priority: true
            show_threat_assessment: true
        performance:
          enabled: true
          size: "medium"
          position:
            x: 4
            y: 2
            width: 4
            height: 2
          refresh_interval_seconds: 30
          parameters:
            show_mission_success_rate: true
            show_threat_detection_rate: true
        alerts:
          enabled: true
          size: "small"
          position:
            x: 8
            y: 0
            width: 4
            height: 1
          refresh_interval_seconds: 1
          parameters:
            show_critical_only: true
            show_threat_alerts: true
        maps:
          enabled: true
          size: "large"
          position:
            x: 0
            y: 4
            width: 6
            height: 2
          refresh_interval_seconds: 2
          parameters:
            show_tactical_zones: true
            show_threat_areas: true
            show_mission_waypoints: true
        analytics:
          enabled: true
          size: "medium"
          position:
            x: 6
            y: 4
            width: 6
            height: 2
          refresh_interval_seconds: 60
          parameters:
            show_mission_analytics: true
            show_threat_analysis: true
        parameters:
          military_specific: true
          tactical_operations: true
          encrypted_display: true
      real_time_updates:
        enabled: true
        update_interval_seconds: 1
        websocket_url: "wss://localhost:8080/ws"
        auto_reconnect: true
        parameters:
          tactical_events: true
          threat_updates: true
          mission_updates: true
      themes:
        default_theme: "tactical"
        available_themes: ["tactical", "night_vision", "classified"]
        dark_mode: true
        parameters:
          color_scheme: "military_green"
      parameters:
        sector: "defense"
        tactical_operations: true
        outdoor_operations: true
        encrypted_communications: true
    websocket:
      enabled: true
      port: 8080
      path: "/ws"
      max_connections: 50
      ping_interval_seconds: 10
      pong_timeout_seconds: 5
      parameters:
        tactical_events: true
        encrypted_messages: true
        threat_updates: true
