apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: atlasmesh-fleet-os
  annotations:
    config.kubernetes.io/local-config: "true"

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: atlasmesh-fleet-os
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/part-of: atlasmesh-fleet-os

# Namespace for all resources
namespace: atlasmesh-fleet-os

# Resources to include
resources:
  - namespace.yaml
  - configmaps/app-config.yaml
  - secrets/api-keys.yaml
  - deployments/control-center-ui.yaml

# Images to update
images:
  - name: atlasmesh/control-center-ui
    newTag: "1.0.0"

# ConfigMap generator for environment-specific configs
configMapGenerator:
  - name: deployment-info
    literals:
      - DEPLOYMENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - DEPLOYMENT_VERSION=1.0.0
      - DEPLOYMENT_ENVIRONMENT=production

# Secret generator for runtime secrets
secretGenerator:
  - name: runtime-secrets
    type: Opaque
    literals:
      - DEPLOYMENT_ID=$(uuidgen)

# Patches for environment-specific customizations
patchesStrategicMerge:
  - patches/production-resources.yaml

# JSON patches for fine-grained modifications
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: control-center-ui
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/deployment.atlasmesh.com~1timestamp
        value: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Replicas for different environments
replicas:
  - name: control-center-ui
    count: 3
