apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-ingestion-config
  namespace: atlasmesh
  labels:
    app: telemetry-ingestion
data:
  config.yaml: |
    # Telemetry Ingestion Service Configuration
    
    # Service Configuration
    port: 8080
    log_level: "info"
    buffer_size: 1000
    redis_ttl_seconds: 300
    
    # Redis Configuration
    redis:
      url: "redis://redis:6379/0"
      pool_size: 10
      min_idle_conns: 5
      max_retries: 3
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
    
    # Kafka Configuration
    kafka:
      brokers: ["kafka:9092"]
      topic_prefix: "telemetry"
      batch_size: 100
      batch_timeout: 1s
      compression: "snappy"
      required_acks: 1
      max_message_bytes: 1048576
    
    # ClickHouse Configuration
    clickhouse:
      url: "http://clickhouse:8123"
      database: "telemetry"
      table: "telemetry_data"
      batch_size: 1000
      flush_interval: 5s
      max_retries: 3
      timeout: 30s
    
    # MinIO Configuration
    minio:
      url: "http://minio:9000"
      access_key: "minioadmin"
      secret_key: "minioadmin"
      bucket: "telemetry-data"
      region: "us-east-1"
      secure: false
    
    # Observability Configuration
    observability:
      metrics:
        enabled: true
        port: 9090
        path: "/metrics"
      tracing:
        enabled: true
        jaeger_endpoint: "http://jaeger-collector:14268/api/traces"
        service_name: "telemetry-ingestion"
      logging:
        level: "info"
        format: "json"
        output: "stdout"
    
    # Performance Configuration
    performance:
      max_concurrent_requests: 1000
      request_timeout: 30s
      response_timeout: 5s
      max_request_size: 10485760  # 10MB
      max_batch_size: 1000
    
    # Security Configuration
    security:
      rate_limit:
        enabled: true
        requests_per_second: 1000
        burst: 2000
      authentication:
        enabled: true
        jwt_secret: "your-jwt-secret"
        api_key_header: "X-API-Key"
      authorization:
        enabled: true
        rbac_enabled: true
        policy_engine_url: "http://policy-engine:8080"
    
    # Health Check Configuration
    health:
      enabled: true
      path: "/health"
      interval: 30s
      timeout: 5s
      retries: 3
      dependencies:
        - redis
        - kafka
        - clickhouse
        - minio
