apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: telemetry-ingestion
  namespace: atlasmesh
  labels:
    app: telemetry-ingestion
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: telemetry-ingestion
