# AtlasMesh Fleet OS - Documentation Site Configuration
# MkDocs Material with Kroki integration for diagrams-as-code

site_name: AtlasMesh Fleet OS
site_description: Vehicle-agnostic, platform-agnostic, sector-agnostic L4 autonomous fleet operating system
site_author: AtlasMesh Engineering Team
site_url: https://docs.atlasmesh.com

# Repository information
repo_name: AtlasMesh-Fleet-OS
repo_url: https://github.com/atlasmesh/fleet-os
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 AtlasMesh Technologies

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  
  # Theme features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  # Color palette
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Fonts
  font:
    text: Roboto
    code: Roboto Mono

  # Logo and favicon
  logo: assets/images/atlasmesh-logo.svg
  favicon: assets/images/favicon.ico

  # Language
  language: en

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: atlasmesh/fleet-os
      branch: main
  - kroki:
      ServerURL: https://kroki.io
      FencePrefix: kroki-
      EnableBlockDiag: true
      EnableBpmn: true
      EnableExcalidraw: true
      EnableMermaid: true
      EnableStructurizr: true
      EnableC4PlantUML: false
  - mermaid2:
      version: 10.6.1
  - awesome-pages
  - macros:
      module_name: docs/macros
  - tags:
      tags_file: tags.md

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: atlasmesh
      repo: fleet-os
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation structure
nav:
  - Home: index.md
  
  - Architecture:
    - architecture/index.md
    - Overview: architecture/overview.md
    - C4 Model: 
      - architecture/c4/index.md
      - System Context: architecture/c4/context.md
      - Container View: architecture/c4/container.md
      - Component View: architecture/c4/component.md
    - Decision Records: architecture/adr/
    
  - Diagrams:
    - diagrams/index.md
    - Safety Critical:
      - diagrams/safety-critical/index.md
      - Emergency Stop: diagrams/safety-critical/emergency-stop.md
      - Command Dispatch: diagrams/safety-critical/command-dispatch.md
      - Autonomy Fallback: diagrams/safety-critical/autonomy-fallback.md
    - System Flows:
      - diagrams/flows/index.md
      - Authentication: diagrams/flows/authentication.md
      - Telemetry Pipeline: diagrams/flows/telemetry.md
      - Data Processing: diagrams/flows/data-processing.md
    - Data Models:
      - diagrams/data/index.md
      - Fleet Database: diagrams/data/fleet-erd.md
      - API Topology: diagrams/data/api-topology.md
    - Security:
      - diagrams/security/index.md
      - Threat Models: diagrams/security/threat-models.md
      - Data Flow Security: diagrams/security/data-flow.md
    - Edge Stack:
      - diagrams/edge/index.md
      - ROS2 Nodes: diagrams/edge/ros2-nodes.md
      - Vehicle Agent: diagrams/edge/vehicle-agent.md

  - API Reference:
    - api/index.md
    - Core Services:
      - Fleet Manager: api/fleet-manager.md
      - Vehicle Gateway: api/vehicle-gateway.md
      - Policy Engine: api/policy-engine.md
      - Auth Service: api/auth-service.md
    - Data Services:
      - Telemetry Ingest: api/telemetry-ingest.md
      - Analytics Engine: api/analytics-engine.md
      - Data Lineage: api/data-lineage.md
    - Integration:
      - UAE Government: api/uae-integration.md
      - Weather Fusion: api/weather-fusion.md
      - Map Data Contract: api/map-data-contract.md

  - Development:
    - development/index.md
    - Getting Started: development/getting-started.md
    - Local Development: development/local-setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Code Standards: development/code-standards.md
    - Diagrams as Code: development/diagrams-as-code.md

  - Operations:
    - operations/index.md
    - Deployment: operations/deployment.md
    - Monitoring: operations/monitoring.md
    - Troubleshooting: operations/troubleshooting.md
    - Runbooks: operations/runbooks/
    - Security: operations/security.md

  - Strategy:
    - strategy/index.md
    - Executive Summary: strategy/executive-summary.md
    - Market Analysis: strategy/market-analysis.md
    - Product Roadmap: strategy/product-roadmap.md
    - Technical Vision: strategy/technical-vision.md

  - Compliance:
    - compliance/index.md
    - UAE Regulations: compliance/uae-regulations.md
    - Safety Standards: compliance/safety-standards.md
    - Data Privacy: compliance/data-privacy.md
    - Audit Trail: compliance/audit-trail.md

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/diagrams.css

extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/diagrams.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra configuration
extra:
  version:
    provider: mike
    default: latest
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/atlasmesh/fleet-os
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/atlasmesh
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/atlasmesh
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/atlasmesh/fleet-os/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you found lacking</a>.

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Watch additional files
watch:
  - docs/
  - mkdocs.yml
  - Makefile.diagrams