apiVersion: v1
kind: Namespace
metadata:
  name: atlasmesh-logistics
  labels:
    sector: logistics
    environment: production
    app.kubernetes.io/name: atlasmesh-fleet-os
    app.kubernetes.io/component: logistics-sector
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: logistics-quota
  namespace: atlasmesh-logistics
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: logistics-limits
  namespace: atlasmesh-logistics
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: "100m"
      memory: 256Mi
    type: Container

