# Open Policy Agent (OPA) Configuration for AtlasMesh Fleet OS
# Configures OPA for authorization decisions and policy evaluation

# Server Configuration
server:
  addr: ":8181"
  diagnostic_addr: ":8282"
  
# Services Configuration
services:
  authz:
    url: http://auth-service:8080
    credentials:
      bearer:
        token: "${AUTHZ_TOKEN}"
        
  audit:
    url: http://audit-service:8080
    
# Bundles Configuration (for policy distribution)
bundles:
  atlasmesh:
    resource: "/policies"
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20
    signing:
      keyid: "atlasmesh_policy_key"
      scope: "read"

# Decision Logging
decision_logs:
  console: true
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10
    
# Status Reporting
status:
  console: true
  
# Plugins Configuration
plugins:
  # Envoy External Authorization
  envoy_ext_authz_grpc:
    addr: ":9191"
    enable_reflection: true
    
# Storage Configuration
storage:
  disk:
    directory: "/tmp/opa"
    
# Caching Configuration  
caching:
  inter_query_builtin_cache:
    max_size_bytes: 100000000 # 100MB
    
# Performance Configuration
nd_builtin_cache: true
wasm_resolver: "oci"

# Distributed Tracing
distributed_tracing:
  type: jaeger
  address: http://jaeger:14268/api/traces
  service_name: "opa-authz"
  
# Metrics
metrics:
  prometheus:
    http_request_duration_seconds:
      buckets:
        - 0.005
        - 0.01
        - 0.025
        - 0.05
        - 0.1
        - 0.25
        - 0.5
        - 1
        - 2.5
        - 5
        - 10
