---
# Logistics Yard ODD Configuration
# Operational Design Domain for autonomous yard tractor operations

odd_id: "logistics_yard_rules_v1"
sector: "logistics"
description: "Operational parameters for autonomous yard tractors in distribution centers, terminals, and logistics yards"
version: "1.0.0"
last_updated: "2025-09-13"
owner: "Logistics Sector Lead"

# Geographic constraints
geographic:
  facility_types:
    - "distribution_center"
    - "container_terminal"
    - "cross_dock_facility"
    - "intermodal_yard"
    - "manufacturing_facility"
  area_types:
    - "yard"
    - "dock_approach"
    - "staging_area"
    - "gate_area"
    - "parking_area"
  surface_types:
    - "concrete"
    - "asphalt"
    - "gravel_compacted"
    - "interlock_pavers"
  slope_limits:
    max_grade_percent: 8
    max_cross_slope_percent: 4
    dock_approach_max_grade_percent: 10

# Road and path constraints
road:
  lane_types:
    - "two_way_traffic"
    - "one_way_traffic"
    - "dock_approach"
    - "trailer_parking"
    - "staging_lane"
    - "gate_lane"
  width_requirements:
    min_width_meters: 4.0
    preferred_width_meters: 5.5
    dock_approach_min_width_meters: 4.5
    trailer_parking_width_meters: 4.0
  markings:
    required:
      - "lane_boundaries"
      - "stop_lines"
      - "dock_spot_markers"
      - "pedestrian_crossings"
    optional:
      - "trailer_parking_guidelines"
      - "staging_area_markings"
      - "directional_arrows"
  obstacles:
    detection_range_meters: 30
    classification_required:
      - "pedestrian"
      - "light_vehicle"
      - "yard_truck"
      - "forklift"
      - "stationary_trailer"
      - "dock_equipment"
      - "temporary_obstacle"

# Weather constraints
weather:
  temperature:
    min_celsius: -30
    max_celsius: 55
    derating_curve:
      - threshold_celsius: 45
        speed_factor: 0.9
      - threshold_celsius: 50
        speed_factor: 0.7
  visibility:
    min_meters: 20
    preferred_meters: 50
    degraded_operations:
      threshold_meters: 30
      speed_factor: 0.5
  precipitation:
    operation_in_rain: true
    operation_in_snow:
      max_depth_cm: 5
      plowed_areas_only: true
    ice_conditions:
      operations_allowed: false
      exception_areas:
        - "covered_yard"
        - "heated_surfaces"

# Time constraints
time:
  operations:
    - "day"
    - "night"
    - "twilight"
  shift_change_considerations:
    buffer_minutes: 15
    handover_locations:
      - "designated_parking_area"
      - "maintenance_facility"

# Communications constraints
communications:
  required_modes:
    primary: "yard_wifi"
    secondary: "private_lte"
    fallback: "cellular"
  gnss_requirements:
    required: true
    augmentation_required: true
    precision_requirements:
      horizontal_meters: 0.3
      vertical_meters: 0.5
    indoor_operations:
      allowed: true
      alternative_localization:
        - "lidar_slam"
        - "visual_markers"
        - "uwb_positioning"
  connectivity_requirements:
    min_uptime_percent: 99.5
    max_outage_minutes: 3
    critical_areas:
      - area: "dock_approach"
        max_outage_seconds: 15
      - area: "gate_operations"
        max_outage_seconds: 15

# Vehicle constraints
vehicle:
  types:
    - "yard_tractor"
    - "terminal_tractor"
  capabilities:
    required_sensors:
      - "lidar"
      - "camera_visual"
      - "radar"
      - "gnss_rtk"
      - "imu"
    specialized_equipment:
      - "fifth_wheel_sensors"
      - "trailer_connection_verification"
      - "kingpin_lock_confirmation"
      - "air_line_connection_detection"
  speed_limits:
    max_speed_kmh: 25
    dock_approach_kmh: 5
    near_pedestrians_kmh: 5
    gate_area_kmh: 10
    blind_corners_kmh: 8
    reverse_operations_kmh: 5
  trailer_operations:
    coupling_verification_required: true
    air_line_connection_verification: true
    landing_gear_position_verification: true
    trailer_presence_confirmation: true

# Interaction constraints
interactions:
  pedestrian_interactions:
    detection_range_meters: 30
    minimum_separation_meters: 3
    crossing_priority: "pedestrian"
    warning_systems_required: true
  vehicle_interactions:
    minimum_separation_meters: 5
    right_of_way_rules:
      - "loaded_has_priority"
      - "dock_approach_has_priority"
      - "main_lane_has_priority"
    passing_rules:
      - "no_passing_in_dock_areas"
      - "no_passing_near_pedestrians"
      - "passing_only_in_designated_areas"
  equipment_interactions:
    - equipment: "forklift"
      minimum_distance_meters: 5
      right_of_way: "forklift"
    - equipment: "reach_stacker"
      minimum_distance_meters: 10
      right_of_way: "reach_stacker"
    - equipment: "straddle_carrier"
      minimum_distance_meters: 15
      right_of_way: "straddle_carrier"
  dock_interactions:
    approach_speed_kmh: 3
    alignment_tolerance_cm: 10
    dock_lock_verification_required: true
    trailer_movement_monitoring_required: true

# Safety constraints
safety:
  pedestrian_safety:
    detection_confidence_threshold: 0.95
    predictive_path_planning: true
    warning_systems:
      - "visual_indicators"
      - "audible_warnings"
      - "projected_path_indicators"
  trailer_safety:
    kingpin_lock_verification: true
    brake_connection_verification: true
    trailer_stability_monitoring: true
    landing_gear_position_verification: true
  dock_safety:
    approach_angle_tolerance_degrees: 5
    distance_monitoring_required: true
    dock_lock_integration: true
    trailer_separation_detection: true
  emergency_protocols:
    emergency_stop_distance:
      pedestrian_meters: 3
      vehicle_meters: 5
    system_fault_response:
      - "controlled_stop"
      - "hazard_indicators"
      - "system_notification"
    recovery_procedures_defined: true

# Operational constraints
operational:
  yard_management_integration:
    move_request_validation: true
    location_reporting: true
    status_updates_frequency_seconds: 30
    exception_handling_procedures: true
  dock_scheduling_integration:
    appointment_awareness: true
    priority_management: true
    dock_availability_verification: true
  gate_operations:
    automated_processing: true
    manual_override_capability: true
    document_verification_integration: true
  tele_assist:
    allowed: true
    max_assists_per_100_moves: 5
    max_duration_minutes_per_assist: 5
    scenarios_requiring_assist:
      - "non_standard_trailer_configuration"
      - "dock_approach_obstruction"
      - "unusual_yard_congestion"
      - "system_uncertainty_high"

# Degradation modes
degradation_modes:
  comms_degraded:
    triggers:
      - "signal_quality_below_threshold"
      - "bandwidth_below_minimum"
      - "latency_above_threshold"
    actions:
      - "reduce_speed_by_30_percent"
      - "increase_separation_distances"
      - "limit_to_known_routes"
  comms_loss:
    triggers:
      - "signal_loss_exceeds_threshold"
      - "heartbeat_failure"
    actions:
      - "complete_current_move_if_safe"
      - "proceed_to_safe_location"
      - "activate_visual_indicators"
  gnss_degraded:
    triggers:
      - "position_uncertainty_exceeds_threshold"
      - "rtk_fix_lost"
    actions:
      - "switch_to_lidar_localization"
      - "reduce_speed_by_50_percent"
      - "restrict_to_well_mapped_areas"
  visibility_degraded:
    triggers:
      - "visibility_below_threshold"
      - "camera_obstruction_detected"
    actions:
      - "reduce_speed_according_to_conditions"
      - "increase_sensing_redundancy"
      - "activate_enhanced_detection_mode"
  trailer_coupling_uncertainty:
    triggers:
      - "kingpin_lock_unconfirmed"
      - "air_line_connection_uncertain"
    actions:
      - "stop_operation"
      - "request_tele_assist"
      - "activate_warning_indicators"

# Testing and validation
validation:
  required_scenarios:
    - "trailer_coupling_uncoupling"
    - "dock_approach_alignment"
    - "pedestrian_interaction"
    - "mixed_traffic_navigation"
    - "low_visibility_operation"
    - "congested_yard_navigation"
  performance_metrics:
    - "move_completion_time"
    - "coupling_accuracy"
    - "dock_approach_precision"
    - "pedestrian_safety_distance_maintenance"
    - "exception_handling_time"
    - "assist_frequency"
