---
# Service Level Objectives (SLOs) for AtlasMesh Fleet OS
# These define the reliability and performance targets for all services

# API Gateway SLOs
api_gateway:
  availability:
    target: 99.95
    measurement_window: "28d"
    error_budget: 21.6  # minutes per 28 days
    
  latency:
    target_p50_ms: 50
    target_p95_ms: 150
    target_p99_ms: 500
    measurement_window: "24h"
    
  throughput:
    min_requests_per_second: 1000
    max_requests_per_second: 10000
    measurement_window: "1h"

# Trip Management SLOs
trip_service:
  availability:
    target: 99.9
    measurement_window: "30d"
    error_budget: 43.2  # minutes per 30 days
    
  trip_creation_latency:
    target_p95_ms: 300
    target_p99_ms: 1000
    measurement_window: "24h"
    
  dispatch_latency:
    target_p50_ms: 200
    target_p95_ms: 500
    target_p99_ms: 2000
    measurement_window: "1h"
    
  assignment_success_rate:
    target: 98.5
    measurement_window: "24h"

# Vehicle Management SLOs  
fleet_manager:
  availability:
    target: 99.95
    measurement_window: "30d"
    error_budget: 21.6  # minutes per 30 days
    
  heartbeat_processing:
    target_p95_ms: 100
    target_p99_ms: 500
    max_processing_delay_s: 5
    measurement_window: "1h"
    
  telemetry_ingestion:
    target_throughput_msgs_per_sec: 10000
    target_p95_latency_ms: 50
    data_loss_rate: 0.001  # 0.1% max loss
    measurement_window: "24h"

# Dispatch and Routing SLOs
dispatch_service:
  availability: 
    target: 99.9
    measurement_window: "30d"
    
  route_calculation:
    target_p50_ms: 500
    target_p95_ms: 2000
    target_p99_ms: 5000
    measurement_window: "1h"
    
  optimization_cycles:
    target_completion_time_s: 30
    target_success_rate: 99.0
    measurement_window: "24h"
    
  eta_accuracy:
    target_mean_error_percent: 10
    target_p90_error_percent: 20
    measurement_window: "7d"

# Weather Service SLOs
weather_service:
  availability:
    target: 99.5
    measurement_window: "30d"
    
  data_freshness:
    target_max_age_minutes: 10
    critical_max_age_minutes: 15
    measurement_window: "24h"
    
  forecast_accuracy:
    temperature_mae_celsius: 2.0
    precipitation_accuracy: 85.0  # percent
    visibility_mae_meters: 100
    measurement_window: "7d"

# Map Service SLOs  
map_service:
  availability:
    target: 99.95
    measurement_window: "30d"
    
  map_tile_delivery:
    target_p95_ms: 200
    target_p99_ms: 1000
    cache_hit_rate: 95.0  # percent
    measurement_window: "24h"
    
  map_data_freshness:
    target_max_age_hours: 1
    critical_max_age_hours: 6
    measurement_window: "24h"

# Tele-Assist SLOs
tele_assist:
  availability:
    target: 99.99  # Higher requirement for safety
    measurement_window: "30d"
    
  connection_establishment:
    target_p95_ms: 1200  # 1.2 seconds
    target_p99_ms: 3000  # 3 seconds  
    measurement_window: "24h"
    
  assist_budget:
    max_assists_per_100_trips: 2.0
    measurement_window: "7d"
    
  resolution_time:
    target_p50_minutes: 5
    target_p95_minutes: 15
    measurement_window: "24h"

# Security and Authentication SLOs
auth_service:
  availability:
    target: 99.99
    measurement_window: "30d"
    
  authentication_latency:
    target_p95_ms: 100
    target_p99_ms: 300
    measurement_window: "1h"
    
  token_validation:
    target_p95_ms: 50
    target_p99_ms: 150
    measurement_window: "1h"

# Policy Engine SLOs
policy_engine:
  availability:
    target: 99.99  # Critical for safety decisions
    measurement_window: "30d"
    
  policy_evaluation:
    target_p50_ms: 50
    target_p95_ms: 200
    target_p99_ms: 500
    measurement_window: "1h"
    
  policy_consistency:
    target_success_rate: 99.99
    measurement_window: "24h"

# Data Pipeline SLOs
data_pipeline:
  availability:
    target: 99.5
    measurement_window: "30d"
    
  event_processing_lag:
    target_p95_seconds: 10
    target_p99_seconds: 60
    measurement_window: "24h"
    
  data_quality:
    schema_validation_success_rate: 99.9
    data_completeness_rate: 99.5
    measurement_window: "24h"

# ML Model Serving SLOs  
ml_serving:
  availability:
    target: 99.9
    measurement_window: "30d"
    
  prediction_latency:
    target_p95_ms: 100
    target_p99_ms: 500
    measurement_window: "1h"
    
  model_accuracy:
    min_acceptable_accuracy: 95.0  # Model dependent
    accuracy_measurement_window: "7d"
    
  drift_detection:
    max_drift_score: 0.1
    drift_check_interval_hours: 6

# Infrastructure SLOs
infrastructure:
  database_availability:
    target: 99.95
    measurement_window: "30d"
    
  database_query_latency:
    target_p95_ms: 100
    target_p99_ms: 500
    measurement_window: "1h"
    
  message_queue_availability:
    target: 99.9
    measurement_window: "30d"
    
  storage_availability:
    target: 99.99
    measurement_window: "30d"

# Cross-cutting SLOs
reliability:
  incident_response:
    detection_time_minutes: 5    # Time to detect incident
    response_time_minutes: 15   # Time to human response
    resolution_time_hours: 4    # Time to resolve P1 incident
    
  backup_and_recovery:
    backup_success_rate: 99.9
    rto_minutes: 15            # Recovery Time Objective
    rpo_minutes: 5             # Recovery Point Objective
    measurement_window: "30d"

# Business SLOs
business_metrics:
  fleet_utilization:
    target_percent: 75.0
    measurement_window: "30d"
    
  trip_success_rate:
    target_percent: 98.0
    measurement_window: "30d"
    
  customer_satisfaction:
    target_score: 4.2  # Out of 5.0
    measurement_window: "30d"
    
  cost_efficiency:
    cost_per_trip_variance: 10.0  # percent
    measurement_window: "30d"

# Sector-specific SLOs
sector_slos:
  defense:
    mission_completion_rate: 98.5
    communication_uptime: 99.5
    convoy_gap_p95_meters: 120
    
  mining:
    throughput_variance_percent: 5.0
    equipment_uptime: 95.0
    safety_incident_rate: 0.0
    
  logistics:
    on_time_delivery_rate: 97.0
    gate_to_gate_p95_minutes: 45
    proof_of_delivery_rate: 99.8
    
  ride_hail:
    pickup_success_rate: 97.0
    eta_accuracy_p95_percent: 15.0
    customer_rating: 4.3

# Alerting thresholds
alerts:
  # Burn rate alerts for error budgets
  burn_rate_fast: 14.4   # 1 hour burn rate
  burn_rate_slow: 1.0    # 1 day burn rate
  
  # Latency degradation
  latency_degradation_threshold: 1.5  # 1.5x normal latency
  
  # Availability degradation  
  availability_warning_threshold: 0.995  # 99.5%
  availability_critical_threshold: 0.990  # 99.0%
  
  # Resource utilization
  cpu_warning_threshold: 80.0      # percent
  cpu_critical_threshold: 90.0     # percent
  memory_warning_threshold: 85.0   # percent  
  memory_critical_threshold: 95.0  # percent
  disk_warning_threshold: 80.0     # percent
  disk_critical_threshold: 90.0    # percent

# SLO monitoring configuration
monitoring:
  collection_interval_seconds: 60
  evaluation_interval_seconds: 300
  retention_days: 90
  dashboard_refresh_seconds: 30
