{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $service.name }}
    component: {{ $serviceName }}
    {{- include "fleet-os.labels" $ | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ $service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: {{ $service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: {{ $service.name }}
    component: {{ $serviceName }}
{{- end }}
{{- end }}

{{- range $uiName, $ui := .Values.ui }}
{{- if $ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $ui.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $ui.name }}
    component: ui
    {{- include "fleet-os.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ $ui.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ $ui.name }}
    component: ui
{{- end }}
{{- end }}
