version: '3.8'

services:
  sap-ewm-adapter:
    build: .
    container_name: sap-ewm-adapter
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config/sap-ewm.yaml
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=atlasmesh
      - DB_PASSWORD=atlasmesh123
      - DB_NAME=atlasmesh_ewm
      - SAP_EWM_HOST=localhost
      - SAP_EWM_PORT=8000
      - SAP_EWM_CLIENT=100
      - SAP_EWM_USER=admin
      - SAP_EWM_PASSWORD=admin123
      - SAP_EWM_AUTH_TYPE=basic
      - SAP_EWM_SSL_ENABLED=false
      - SAP_EWM_SSL_VERIFY=false
      - SAP_EWM_API_VERSION=v1
      - SAP_EWM_TIMEOUT=30s
      - SAP_EWM_RETRY_ATTEMPTS=3
      - SAP_EWM_RETRY_DELAY=5s
      - SAP_EWM_POLL_INTERVAL=5s
      - SAP_EWM_BATCH_SIZE=100
      - SAP_EWM_QUEUE_SIZE=1000
      - SAP_EWM_WAREHOUSE_ID=WH001
    depends_on:
      - postgres
    networks:
      - atlasmesh-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: sap-ewm-postgres
    environment:
      - POSTGRES_DB=atlasmesh_ewm
      - POSTGRES_USER=atlasmesh
      - POSTGRES_PASSWORD=atlasmesh123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - atlasmesh-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlasmesh -d atlasmesh_ewm"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sap-ewm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - atlasmesh-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  atlasmesh-network:
    driver: bridge
