apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-os-staging
  namespace: argocd
  labels:
    environment: staging
    project: fleet-os
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/atlasmesh/fleet-os.git
    targetRevision: release/v1.0.0
    path: deployment/helm/fleet-os
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: staging-latest
        - name: environment
          value: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: fleet-os-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
