# AtlasMesh Fleet OS - Jaeger Distributed Tracing Configuration
# Comprehensive tracing for Abu Dhabi autonomous vehicle fleet operations
# Tracks request flows across all microservices and edge devices

# Jaeger Collector Configuration
collector:
  # OTLP receiver configuration
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "https://app.atlasmesh.com"
            - "https://app-staging.atlasmesh.com"
            - "http://localhost:3000"
  
  # Jaeger receiver configuration
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_binary:
        endpoint: 0.0.0.0:6832
  
  # Zipkin receiver configuration
  zipkin:
    endpoint: 0.0.0.0:9411

# Query Service Configuration
query:
  # Base path for the query service
  base-path: /
  
  # Additional query options
  query:
    max-clock-skew-adjustment: 0s
    
  # UI Configuration
  ui:
    config-file: /etc/jaeger/ui-config.json
    
  # CORS settings
  http-server:
    host-port: 0.0.0.0:16686
    cors:
      allowed-origins:
        - "https://app.atlasmesh.com"
        - "https://app-staging.atlasmesh.com"
        - "http://localhost:3000"

# Agent Configuration (for edge devices)
agent:
  # Jaeger agent server configuration
  server:
    host-port: 0.0.0.0:5775
    
  # Reporter configuration
  reporter:
    # Batch configuration
    batch:
      size: 100
      timeout: 1s
    
    # Local agent endpoint
    local-agent:
      host-port: jaeger-agent:6831

# Storage Configuration
storage:
  type: elasticsearch
  
  # Elasticsearch configuration
  elasticsearch:
    server-urls: 
      - http://elasticsearch:9200
    
    # Index configuration
    index-prefix: jaeger
    index-date-separator: "-"
    
    # Rollover configuration
    rollover:
      conditions:
        max-age: 7d
        max-size: 50gb
    
    # ILM configuration
    ilm:
      enabled: true
      policy-name: jaeger-ilm-policy
      
    # Template configuration
    create-index-templates: true
    version: 7
    
    # Security configuration
    tls:
      enabled: false
      ca: /etc/ssl/certs/ca.crt
      cert: /etc/ssl/certs/client.crt
      key: /etc/ssl/private/client.key
      server-name: elasticsearch.atlasmesh.local
    
    # Authentication
    basic:
      username: jaeger
      password-file: /etc/jaeger/secrets/elasticsearch_password
    
    # Performance tuning
    bulk:
      size: 5242880  # 5MB
      workers: 10
      flush-interval: 200ms
    
    # Sharding and replication
    num-shards: 5
    num-replicas: 1
    
    # Retention
    max-span-age: 168h  # 7 days

# Sampling Configuration
sampling:
  # Default sampling strategy
  default_strategy:
    type: probabilistic
    param: 0.1  # 10% sampling rate
    
  # Per-service sampling strategies
  per_service_strategies:
    # Critical services - higher sampling
    - service: "api-gateway"
      type: probabilistic
      param: 0.5  # 50% sampling
      max_traces_per_second: 1000
      
    - service: "vehicle-gateway"
      type: probabilistic
      param: 0.8  # 80% sampling for vehicle operations
      max_traces_per_second: 2000
      
    - service: "policy-engine"
      type: probabilistic
      param: 1.0  # 100% sampling for policy decisions
      max_traces_per_second: 500
      
    - service: "fleet-manager"
      type: probabilistic
      param: 0.3  # 30% sampling
      max_traces_per_second: 800
      
    - service: "telemetry-ingestion"
      type: probabilistic
      param: 0.1  # 10% sampling due to high volume
      max_traces_per_second: 5000
      
    # Edge services
    - service: "edge-ros2-stack"
      type: probabilistic
      param: 0.2  # 20% sampling for edge operations
      max_traces_per_second: 1000
      
    # UI services
    - service: "control-center-ui"
      type: probabilistic
      param: 0.1  # 10% sampling for UI operations
      max_traces_per_second: 200
      
    # Abu Dhabi specific services
    - service: "weather-fusion"
      type: probabilistic
      param: 0.5  # 50% sampling for weather data
      max_traces_per_second: 100
      
    - service: "map-data-contract"
      type: probabilistic
      param: 0.7  # 70% sampling for map operations
      max_traces_per_second: 300

# Processor Configuration
processors:
  # Batch processor
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  # Memory limiter
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s
  
  # Resource processor for Abu Dhabi specific attributes
  resource:
    attributes:
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.region
        value: abu_dhabi
        action: upsert
      - key: service.country
        value: uae
        action: upsert
      - key: service.timezone
        value: Asia/Dubai
        action: upsert
  
  # Attribute processor for sensitive data
  attributes:
    actions:
      # Remove sensitive information
      - key: user.password
        action: delete
      - key: api.key
        action: delete
      - key: database.password
        action: delete
      
      # Add fleet-specific attributes
      - key: fleet.region
        value: abu_dhabi
        action: insert
      - key: fleet.operator
        value: atlasmesh
        action: insert

# Extensions Configuration
extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133
    
  # PPROFextension for debugging
  pprof:
    endpoint: 0.0.0.0:1777
    
  # Zpages extension
  zpages:
    endpoint: 0.0.0.0:55679

# Service Configuration
service:
  # Extensions to load
  extensions: [health_check, pprof, zpages]
  
  # Pipeline configuration
  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [jaeger_elasticsearch]
    
    # Metrics pipeline (if collecting trace metrics)
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus]
  
  # Telemetry configuration
  telemetry:
    logs:
      level: info
      development: false
      sampling:
        initial: 5
        thereafter: 200
      encoding: json
      output_paths:
        - stdout
        - /var/log/jaeger/jaeger.log
      error_output_paths:
        - stderr
        - /var/log/jaeger/jaeger-error.log
    
    metrics:
      level: detailed
      address: 0.0.0.0:8888

# Exporters Configuration
exporters:
  # Jaeger exporter to Elasticsearch
  jaeger_elasticsearch:
    endpoint: http://elasticsearch:9200
    index: jaeger-spans
    
  # Prometheus exporter for trace metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: jaeger
    const_labels:
      region: abu_dhabi
      environment: production

# Abu Dhabi Fleet Specific Configuration
fleet:
  # Vehicle tracing configuration
  vehicles:
    # Trace all safety-critical operations
    safety_operations:
      sampling_rate: 1.0
      retention_days: 30
      
    # Trace vehicle commands
    commands:
      sampling_rate: 0.8
      retention_days: 7
      
    # Trace telemetry ingestion
    telemetry:
      sampling_rate: 0.1
      retention_days: 3
  
  # Geofence and compliance tracing
  compliance:
    # Trace all policy evaluations
    policy_decisions:
      sampling_rate: 1.0
      retention_days: 90
      
    # Trace geofence violations
    geofence_violations:
      sampling_rate: 1.0
      retention_days: 30
  
  # Performance monitoring
  performance:
    # Critical latency thresholds
    thresholds:
      policy_evaluation_ms: 50
      vehicle_command_ms: 100
      route_calculation_ms: 500
      
    # Alert on threshold violations
    alerts:
      enabled: true
      webhook_url: https://alerts.atlasmesh.com/webhook/jaeger

# UI Configuration
ui_config:
  # Menu configuration
  menu:
    - label: "Fleet Operations"
      url: "/search?service=fleet-manager"
    - label: "Vehicle Commands"
      url: "/search?service=vehicle-gateway"
    - label: "Policy Decisions"
      url: "/search?service=policy-engine"
    - label: "Safety Incidents"
      url: "/search?tags={\"safety\":\"incident\"}"
  
  # Dependencies configuration
  dependencies:
    menuEnabled: true
    
  # Archive configuration
  archiveEnabled: true
  
  # Tracking configuration
  tracking:
    gaID: "UA-XXXXXXXX-X"  # Google Analytics ID
    trackErrors: true
    
  # Search configuration
  search:
    maxLookback: {
      label: "2 days",
      value: "2d"
    }
    
  # Critical path highlighting
  criticalPath:
    enabled: true
    services:
      - "policy-engine"
      - "vehicle-gateway"
      - "fleet-manager"
