sector: ride_hail
services:
  dispatch:
    dispatch:
      max_concurrent_tasks: 500
      task_prioritization:
        enabled: true
        priority_levels: 3
        emergency_override: true
        dynamic_pricing: true
        parameters:
          surge_pricing: true
          passenger_priority: true
      route_optimization:
        enabled: true
        algorithm: "dijkstra"
        consider_traffic: true
        consider_weather: true
        parameters:
          optimization_timeout_seconds: 10
      load_balancing:
        enabled: true
        strategy: "demand_based"
        max_load_per_vehicle: 1
        parameters:
          passenger_capacity: true
      parameters:
        task_timeout_minutes: 15
        retry_attempts: 2
  routing:
    routing:
      algorithm: "dijkstra"
      consider_traffic: true
      consider_weather: true
      real_time_updates: true
      multi_stop_routing:
        enabled: true
        max_stops_per_route: 5
        optimization_level: "high"
        parameters:
          passenger_pooling: true
          pickup_optimization: true
      dynamic_routing:
        enabled: true
        update_frequency_seconds: 30
        reroute_threshold: 0.3
        parameters:
          traffic_adaptation: true
          passenger_preference: true
      parameters:
        urban_navigation: true
        traffic_law_compliance: true
        passenger_comfort: true
        max_speed_mps: 15.0
  optimization:
    optimization:
      algorithm: "genetic"
      optimization_goals: ["maximize_passenger_satisfaction", "minimize_wait_time", "maximize_revenue"]
      constraints:
        time_windows: true
        capacity_limits: true
        vehicle_compatibility: true
        parameters:
          passenger_requirements: true
          service_level_agreement: true
      performance_tuning:
        max_optimization_time_seconds: 30
        parallel_processing: true
        cache_results: true
        parameters:
          passenger_metrics: true
      parameters:
        optimization_interval_seconds: 60
        demand_forecasting: true