# AtlasMesh Fleet OS - Production Environment Configuration
# Abu Dhabi autonomous vehicle fleet management platform
# Production environment with maximum security, performance, and compliance

environment: production
region: abu_dhabi
timezone: Asia/Dubai

# API Configuration
api:
  base_url: https://api.atlasmesh.com
  ws_url: wss://api.atlasmesh.com
  timeout: 30000
  rate_limit:
    requests_per_minute: 10000
    burst_size: 200
  cors:
    enabled: true
    origins:
      - https://app.atlasmesh.com
      - https://fleet.atlasmesh.com

# Database Configuration
database:
  postgresql:
    host: postgresql-prod-cluster.atlasmesh.local
    port: 5432
    database: atlasmesh_fleet
    username: atlasmesh_prod
    password_env: POSTGRES_PASSWORD_PROD
    ssl_mode: require
    max_connections: 200
    connection_timeout: 30s
    idle_timeout: 300s
    log_queries: false
    
    # High availability configuration
    ha:
      enabled: true
      read_replicas: 3
      failover_timeout: 30s
      backup_retention: 30d
  
  redis:
    cluster:
      enabled: true
      nodes:
        - redis-prod-01.atlasmesh.local:6379
        - redis-prod-02.atlasmesh.local:6379
        - redis-prod-03.atlasmesh.local:6379
        - redis-prod-04.atlasmesh.local:6379
        - redis-prod-05.atlasmesh.local:6379
        - redis-prod-06.atlasmesh.local:6379
    password_env: REDIS_PASSWORD_PROD
    max_connections: 100
    connection_timeout: 5s
    idle_timeout: 300s
    ssl: true

# Message Queue Configuration
messaging:
  kafka:
    brokers:
      - kafka-prod-01.atlasmesh.local:9092
      - kafka-prod-02.atlasmesh.local:9092
      - kafka-prod-03.atlasmesh.local:9092
      - kafka-prod-04.atlasmesh.local:9092
      - kafka-prod-05.atlasmesh.local:9092
    topic_prefix: atlasmesh_prod
    consumer_group: atlasmesh_prod_group
    security:
      protocol: SASL_SSL
      mechanism: SCRAM-SHA-256
      username: atlasmesh_prod
      password_env: KAFKA_PASSWORD_PROD
    performance:
      batch_size: 1000
      linger_ms: 5
      buffer_memory: 134217728
      compression_type: lz4
    
    # High availability
    ha:
      replication_factor: 3
      min_in_sync_replicas: 2
      unclean_leader_election: false

# Map Configuration (Abu Dhabi centered)
maps:
  default_provider: openstreetmap
  default_center:
    lat: 24.4539
    lng: 54.3773
  default_zoom: 12
  providers:
    openstreetmap:
      enabled: true
      tile_server: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
      attribution: "© OpenStreetMap contributors"
      cache_ttl: 3600
    google:
      enabled: true
      api_key_env: GOOGLE_MAPS_API_KEY_PROD
      map_type: roadmap
      rate_limit: 100000
    mapbox:
      enabled: false
      api_key_env: MAPBOX_API_KEY_PROD
  
  # Abu Dhabi specific settings
  abu_dhabi:
    bounds:
      north: 24.6
      south: 24.2
      east: 55.0
      west: 54.0
    districts:
      - abu_dhabi_city
      - al_ain
      - al_dhafra
    landmarks:
      - sheikh_zayed_mosque
      - emirates_palace
      - corniche
      - yas_island
    
    # High-definition map data
    hd_maps:
      enabled: true
      provider: lanelet2
      update_frequency: daily
      validation: strict

# Feature Flags
features:
  enable_clustering: true
  enable_real_time_updates: true
  enable_vehicle_trails: true
  enable_geofence_monitoring: true
  enable_heatmaps: false
  enable_offline_mode: false
  enable_debug_mode: false
  enable_mock_data: false
  enable_performance_monitoring: true
  enable_chaos_engineering: false

# Performance Settings
performance:
  map_update_interval: 5000
  telemetry_batch_size: 100
  max_vehicles_on_map: 200
  max_route_points: 1000
  cluster_radius: 50
  max_cluster_zoom: 15
  
  # Strict production budgets
  budgets:
    policy_evaluation_ms: 25
    vehicle_command_ms: 50
    route_calculation_ms: 200
    ui_render_ms: 30
    
  # SLA requirements
  sla:
    availability: 99.95
    response_time_p95: 100
    error_rate_max: 0.1

# Security Configuration
security:
  enable_https: true
  hsts_enabled: true
  csrf_token_header: X-CSRF-Token
  
  jwt:
    secret_env: JWT_SECRET_PROD
    expiration: 1h
    refresh_expiration: 8h
    algorithm: RS256
    
  # Production authentication
  auth:
    bypass_enabled: false
    require_mfa: true
    session_timeout: 4h
    password_policy:
      min_length: 12
      require_special_chars: true
      require_numbers: true
      require_uppercase: true
      require_lowercase: true
      history_count: 12
    
    # Account lockout
    lockout:
      max_attempts: 3
      lockout_duration: 30m
      
  # Network security
  network:
    waf_enabled: true
    ddos_protection: true
    ip_whitelist_enabled: true
    geo_blocking:
      enabled: true
      allowed_countries: [AE, US, GB, DE]
  
  # Data encryption
  encryption:
    at_rest: true
    in_transit: true
    key_rotation: true
    algorithm: AES-256-GCM

# Logging Configuration
logging:
  level: warn
  format: json
  output:
    - elasticsearch
    - siem
  
  elasticsearch:
    cluster:
      - elasticsearch-prod-01.atlasmesh.local:9200
      - elasticsearch-prod-02.atlasmesh.local:9200
      - elasticsearch-prod-03.atlasmesh.local:9200
    index: atlasmesh-prod-logs
    username: fluentd_prod
    password_env: ELASTICSEARCH_PASSWORD_PROD
    ssl: true
    
  siem:
    enabled: true
    endpoint: https://siem.atlasmesh.com/api/logs
    api_key_env: SIEM_API_KEY_PROD
    
  # Audit logging
  audit:
    enabled: true
    events:
      - user_login
      - user_logout
      - policy_change
      - vehicle_command
      - emergency_stop
      - data_access
    retention: 7y
  
  components:
    policy_engine: warn
    vehicle_gateway: warn
    fleet_manager: warn
    telemetry_ingestion: error
    map_data_contract: warn
    weather_fusion: warn

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    metrics_path: /metrics
    retention: 90d
    
    # High availability
    ha:
      enabled: true
      replicas: 3
      
  grafana:
    enabled: true
    port: 3000
    admin_password_env: GRAFANA_ADMIN_PASSWORD_PROD
    
    # Enterprise features
    enterprise:
      enabled: true
      license_env: GRAFANA_LICENSE_PROD
      
  jaeger:
    enabled: true
    collector_endpoint: https://jaeger-prod.atlasmesh.local:14268
    sampling_rate: 0.1
    
  health_checks:
    enabled: true
    interval: 15s
    timeout: 5s
    
  # Alerting
  alerting:
    enabled: true
    channels:
      - type: pagerduty
        integration_key_env: PAGERDUTY_KEY_PROD
      - type: slack
        webhook_url_env: SLACK_WEBHOOK_PROD
      - type: email
        smtp_host: smtp.atlasmesh.com
        from: alerts@atlasmesh.com

# External Services (Production)
external_services:
  weather_api:
    enabled: true
    mock: false
    url: https://api.openweathermap.org/data/2.5
    api_key_env: WEATHER_API_KEY_PROD
    timeout: 5s
    rate_limit: 10000
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      timeout: 30s
  
  traffic_api:
    enabled: true
    mock: false
    url: https://api.tomtom.com/traffic/services/4
    api_key_env: TRAFFIC_API_KEY_PROD
    timeout: 10s
    rate_limit: 5000
    circuit_breaker:
      enabled: true
      failure_threshold: 3
      timeout: 60s
  
  uae_government_apis:
    enabled: true
    mock: false
    base_url: https://api.government.ae
    api_key_env: UAE_GOV_API_KEY_PROD
    timeout: 30s
    rate_limit: 1000
    circuit_breaker:
      enabled: true
      failure_threshold: 2
      timeout: 120s

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: 90d
  
  storage:
    primary:
      type: s3
      bucket: atlasmesh-prod-backups
      region: me-south-1
      encryption: true
      versioning: true
    
    secondary:
      type: s3
      bucket: atlasmesh-prod-backups-dr
      region: eu-west-1
      encryption: true
      cross_region_replication: true
  
  # Backup validation
  validation:
    enabled: true
    restore_test_frequency: weekly
    integrity_check: daily

# Secrets Management
secrets:
  provider: vault
  rotation: true
  rotation_schedule: "0 3 * * 0"  # Weekly
  
  vault:
    address: https://vault.atlasmesh.com
    auth_method: kubernetes
    role: atlasmesh-prod
    mount_path: secret/atlasmesh/prod
    
    # Secret paths
    paths:
      database: database/credentials
      messaging: messaging/credentials
      api_keys: external/api_keys
      certificates: tls/certificates
      jwt: auth/jwt_secrets

# Resource Limits (Production)
resources:
  cpu_limit: 16000m
  memory_limit: 32Gi
  storage_limit: 1Ti
  
  # Per-service limits with autoscaling
  services:
    api_gateway:
      cpu: 1000m
      memory: 1Gi
      replicas:
        min: 3
        max: 10
        target_cpu: 70
    fleet_manager:
      cpu: 500m
      memory: 1Gi
      replicas:
        min: 3
        max: 8
        target_cpu: 70
    policy_engine:
      cpu: 500m
      memory: 1Gi
      replicas:
        min: 3
        max: 6
        target_cpu: 60
    vehicle_gateway:
      cpu: 1000m
      memory: 2Gi
      replicas:
        min: 5
        max: 15
        target_cpu: 70
    telemetry_ingestion:
      cpu: 1000m
      memory: 2Gi
      replicas:
        min: 3
        max: 12
        target_cpu: 80
    control_center_ui:
      cpu: 500m
      memory: 512Mi
      replicas:
        min: 3
        max: 8
        target_cpu: 70

# Compliance (Full production compliance)
compliance:
  uae_regulations: true
  iso_standards: true
  gdpr: true
  audit_logging: true
  data_retention: 7y
  
  # Standards compliance
  standards:
    iso_27001: true
    iso_21448: true
    soc2_type2: true
    
  # Compliance validation
  validation:
    automated_checks: true
    manual_reviews: true
    third_party_audits: true
    frequency: quarterly
  
  # Data governance
  data_governance:
    classification: enabled
    lineage_tracking: enabled
    access_controls: strict
    retention_policies: enforced

# Disaster Recovery
disaster_recovery:
  enabled: true
  rto: 1h
  rpo: 15m
  backup_frequency: continuous
  cross_region_replication: true
  
  # Multi-region setup
  regions:
    primary: me-south-1
    secondary: eu-west-1
    
  # Failover configuration
  failover:
    automatic: true
    health_check_interval: 30s
    failure_threshold: 3
    rollback_timeout: 15m

# Network Configuration
network:
  vpc_cidr: 10.0.0.0/16
  
  subnets:
    public:
      - 10.0.1.0/24
      - 10.0.2.0/24
      - 10.0.3.0/24
    private:
      - 10.0.10.0/24
      - 10.0.11.0/24
      - 10.0.12.0/24
    database:
      - 10.0.20.0/24
      - 10.0.21.0/24
      - 10.0.22.0/24
  
  # Load balancer configuration
  load_balancer:
    type: application
    scheme: internet-facing
    ssl_policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    deletion_protection: true
    
  # WAF configuration
  waf:
    enabled: true
    rules:
      - aws_managed_core_rule_set
      - aws_managed_known_bad_inputs
      - aws_managed_sql_injection
      - aws_managed_linux_rule_set
      - custom_rate_limiting
    
  # VPN configuration
  vpn:
    enabled: true
    type: site_to_site
    customer_gateway: 203.0.113.1
    
  # NAT Gateway
  nat_gateway:
    enabled: true
    high_availability: true

# Cost Optimization
cost_optimization:
  enabled: true
  
  # Resource optimization
  resource_optimization:
    right_sizing: enabled
    unused_resources: cleanup
    reserved_instances: enabled
    
  # Storage optimization
  storage_optimization:
    lifecycle_policies: enabled
    compression: enabled
    deduplication: enabled
    
  # Monitoring
  cost_monitoring:
    budgets: enabled
    alerts: enabled
    reports: weekly

# Abu Dhabi Specific Configuration
abu_dhabi:
  # Local regulations
  regulations:
    uae_av_law: compliant
    adm_requirements: compliant
    data_residency: enforced
    
  # Local integrations
  integrations:
    traffic_management_system: enabled
    emergency_services: enabled
    weather_services: enabled
    
  # Cultural considerations
  cultural:
    language_support: [en, ar]
    timezone: Asia/Dubai
    calendar: gregorian
    weekend: [friday, saturday]
