---
# Defense Sector Configuration
# Specialized settings for military/defense operations

sector: "defense"
description: "Military and defense sector operations with enhanced security and operational requirements"

# Priority model for dispatch decisions
priority_model: "mission_first"
dispatch_strategy: "security_optimized"

# Safety margins and operational constraints
safety_margins:
  following_distance_m: 50  # Increased for convoy operations
  convoy_spacing_m: 100     # Minimum inter-vehicle spacing
  lateral_clearance_m: 2.0  # Side clearance from obstacles
  emergency_brake_distance_m: 30

# Operational parameters
operational_constraints:
  max_convoy_size: 12
  min_convoy_size: 2
  max_speed_convoy_kmh: 45  # Reduced for formation keeping
  max_speed_solo_kmh: 65
  night_operations: true
  gps_denied_operation: true

# KPIs and performance targets
kpis:
  assist_budget_per_100_trips: 1.0  # Stricter than civilian
  max_eta_variance: 0.15           # 15% variance allowed
  convoy_gap_p95_m: 120            # 95th percentile gap tolerance
  mission_completion_rate: 0.98    # 98% mission success rate
  communication_uptime: 0.995      # 99.5% communications availability

# Special requirements and constraints
special_requirements:
  encrypted_communications: true
  operational_security: "classified"
  gps_denied_operation: true
  electronic_warfare_resilience: true
  battle_damage_assessment: true
  chemical_detection: false        # Vehicle dependent

# Communications and networking
communications:
  primary_network: "tactical_radio"
  backup_network: "satellite"
  mesh_networking: true
  frequency_hopping: true
  encryption_standard: "aes_256"
  comsec_key_management: true

# Route planning constraints
route_constraints:
  avoid_populated_areas: true
  prefer_hardened_roads: true
  bridge_weight_limits: true
  obstacle_clearance_height_m: 4.5
  turning_radius_constraint: true
  tactical_waypoints_required: true

# Weather and environmental constraints
environmental_limits:
  max_dust_concentration_ugm3: 2000  # Higher tolerance than civilian
  min_visibility_m: 100              # Can operate in lower visibility
  max_crosswind_kmh: 80
  temperature_range:
    min_celsius: -40
    max_celsius: 60
  altitude_range:
    min_meters: -100
    max_meters: 4000

# Security and compliance
security_requirements:
  classification_level: "secret"
  personnel_clearance_required: "secret"
  vehicle_security_check: true
  cargo_inspection: true
  route_classification: "restricted"
  opsec_protocols: true

# Maintenance and logistics
maintenance_constraints:
  field_maintenance_capability: true
  spare_parts_availability: "mission_critical"
  maintenance_window_hours: 4      # Reduced maintenance windows
  operational_availability: 0.95   # 95% availability requirement

# Training and certification requirements
training_requirements:
  operator_certification: "defense_qualified"
  tactical_driving: true
  convoy_operations: true
  emergency_procedures: true
  communications_protocols: true

# Integration with military systems
system_integrations:
  command_control_system: "c2_integration_required"
  blue_force_tracker: true
  situational_awareness: "real_time"
  intelligence_feeds: true
  logistics_system: "military_erp"

# Threat response and security
threat_response:
  threat_detection: "active"
  evasive_maneuvers: true
  defensive_driving: true
  emergency_protocols: "military_standard"
  escalation_procedures: true

# Operational planning
mission_planning:
  route_reconnaissance: true
  threat_assessment: true
  weather_analysis: true
  timing_coordination: true
  contingency_planning: true
  abort_criteria: true

# Data handling and reporting
data_requirements:
  classification_handling: "secret"
  data_retention_days: 2555  # 7 years for military records
  audit_trail: "complete"
  incident_reporting: "immediate"
  performance_metrics: "classified"

# Regional considerations for Middle East
regional_specifics:
  desert_operations: true
  extreme_heat_procedures: true
  sand_storm_protocols: true
  cultural_considerations: true
  local_coordination: "required"
