# AtlasMesh Fleet OS - Prometheus Alerting Rules

groups:
- name: fleet-os-critical
  rules:
  # System Health Alerts
  - alert: ServiceDown
    expr: up{job=~"fleet-manager|vehicle-gateway|policy-engine|api-gateway"} == 0
    for: 1m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Critical service {{ $labels.job }} is down"
      description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."
      runbook_url: "https://docs.atlasmesh.ae/runbooks/service-down"

  - alert: HighErrorRate
    expr: |
      (
        rate(http_requests_total{status=~"5.."}[5m]) /
        rate(http_requests_total[5m])
      ) > 0.05
    for: 5m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "High error rate detected on {{ $labels.service }}"
      description: "Error rate is {{ $value | humanizePercentage }} for service {{ $labels.service }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/high-error-rate"

  - alert: HighLatency
    expr: |
      histogram_quantile(0.95, 
        rate(http_request_duration_seconds_bucket[5m])
      ) > 2
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "High latency detected on {{ $labels.service }}"
      description: "95th percentile latency is {{ $value }}s for service {{ $labels.service }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/high-latency"

- name: fleet-os-business
  rules:
  # Fleet Operations Alerts
  - alert: FleetUtilizationLow
    expr: fleet_utilization_percentage < 50
    for: 10m
    labels:
      severity: warning
      team: operations
    annotations:
      summary: "Fleet utilization is low"
      description: "Fleet utilization is {{ $value }}%, below 50% threshold"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/fleet-utilization"

  - alert: EmergencyStopsHigh
    expr: increase(emergency_stops_total[1h]) > 5
    for: 1m
    labels:
      severity: critical
      team: safety
    annotations:
      summary: "High number of emergency stops"
      description: "{{ $value }} emergency stops in the last hour"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/emergency-stops"

  - alert: AssistRequestsHigh
    expr: rate(assist_requests_total[5m]) > 0.167  # 10 per hour
    for: 5m
    labels:
      severity: warning
      team: operations
    annotations:
      summary: "High assist request rate"
      description: "Assist request rate is {{ $value | humanize }} per second"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/assist-requests"

  - alert: TripAssignmentFailure
    expr: |
      (
        rate(trip_assignments_failed_total[5m]) /
        rate(trip_assignments_total[5m])
      ) > 0.05
    for: 5m
    labels:
      severity: warning
      team: operations
    annotations:
      summary: "High trip assignment failure rate"
      description: "Trip assignment failure rate is {{ $value | humanizePercentage }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/trip-assignment"

- name: fleet-os-infrastructure
  rules:
  # Database Alerts
  - alert: DatabaseConnectionsHigh
    expr: |
      (
        pg_stat_database_numbackends /
        pg_settings_max_connections
      ) > 0.8
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Database connections approaching limit"
      description: "Database connections at {{ $value | humanizePercentage }} of maximum"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/database-connections"

  - alert: DatabaseReplicationLag
    expr: pg_replication_lag_seconds > 30
    for: 2m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Database replication lag is high"
      description: "Replication lag is {{ $value }}s"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/database-replication"

  # Kafka Alerts
  - alert: KafkaConsumerLag
    expr: kafka_consumer_lag_sum > 10000
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Kafka consumer lag is high"
      description: "Consumer lag is {{ $value }} messages for topic {{ $labels.topic }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/kafka-lag"

  - alert: KafkaDLQMessages
    expr: rate(kafka_dlq_messages_total[5m]) > 10
    for: 2m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "High rate of DLQ messages"
      description: "DLQ message rate is {{ $value }} per second for topic {{ $labels.topic }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/kafka-dlq"

  # Redis Alerts
  - alert: RedisMemoryUsageHigh
    expr: |
      (
        redis_memory_used_bytes /
        redis_memory_max_bytes
      ) > 0.9
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Redis memory usage is high"
      description: "Redis memory usage is {{ $value | humanizePercentage }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/redis-memory"

- name: fleet-os-edge
  rules:
  # Edge/Vehicle Alerts
  - alert: VehicleOffline
    expr: vehicle_heartbeat_seconds > 60
    for: 2m
    labels:
      severity: critical
      team: edge
    annotations:
      summary: "Vehicle {{ $labels.vehicle_id }} is offline"
      description: "Vehicle {{ $labels.vehicle_id }} last heartbeat was {{ $value }}s ago"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/vehicle-offline"

  - alert: ControlLoopLatencyHigh
    expr: control_loop_latency_seconds > 0.05  # 50ms
    for: 1m
    labels:
      severity: critical
      team: edge
    annotations:
      summary: "Control loop latency is high on {{ $labels.vehicle_id }}"
      description: "Control loop latency is {{ $value }}s on vehicle {{ $labels.vehicle_id }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/control-loop-latency"

  - alert: SensorHealthLow
    expr: sensor_health_score < 80
    for: 5m
    labels:
      severity: warning
      team: edge
    annotations:
      summary: "Sensor health is low on {{ $labels.vehicle_id }}"
      description: "Sensor health score is {{ $value }}% on vehicle {{ $labels.vehicle_id }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/sensor-health"

  - alert: VehicleBatteryLow
    expr: vehicle_battery_percentage < 20
    for: 1m
    labels:
      severity: warning
      team: operations
    annotations:
      summary: "Vehicle {{ $labels.vehicle_id }} battery is low"
      description: "Battery level is {{ $value }}% on vehicle {{ $labels.vehicle_id }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/vehicle-battery"

- name: fleet-os-security
  rules:
  # Security Alerts
  - alert: FailedAuthenticationHigh
    expr: rate(authentication_failures_total[5m]) > 1
    for: 2m
    labels:
      severity: warning
      team: security
    annotations:
      summary: "High rate of authentication failures"
      description: "Authentication failure rate is {{ $value }} per second"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/auth-failures"

  - alert: UnauthorizedAccessAttempt
    expr: rate(unauthorized_access_attempts_total[5m]) > 0.1
    for: 1m
    labels:
      severity: critical
      team: security
    annotations:
      summary: "Unauthorized access attempts detected"
      description: "Unauthorized access attempt rate is {{ $value }} per second"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/unauthorized-access"

  - alert: CertificateExpiringSoon
    expr: (cert_expiry_timestamp - time()) / 86400 < 30
    for: 1h
    labels:
      severity: warning
      team: security
    annotations:
      summary: "Certificate {{ $labels.cert_name }} expiring soon"
      description: "Certificate expires in {{ $value }} days"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/certificate-expiry"

- name: fleet-os-compliance
  rules:
  # Compliance and Evidence Alerts
  - alert: EvidenceQueueHigh
    expr: evidence_queue_depth > 1000
    for: 5m
    labels:
      severity: warning
      team: compliance
    annotations:
      summary: "Evidence queue depth is high"
      description: "Evidence queue has {{ $value }} items"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/evidence-queue"

  - alert: EvidenceUploadFailure
    expr: |
      (
        rate(evidence_uploads_failed_total[5m]) /
        rate(evidence_uploads_total[5m])
      ) > 0.05
    for: 5m
    labels:
      severity: warning
      team: compliance
    annotations:
      summary: "High evidence upload failure rate"
      description: "Evidence upload failure rate is {{ $value | humanizePercentage }}"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/evidence-upload"

  - alert: ComplianceViolation
    expr: compliance_violations_total > 0
    for: 1m
    labels:
      severity: critical
      team: compliance
    annotations:
      summary: "Compliance violation detected"
      description: "{{ $value }} compliance violations detected"
      runbook_url: "https://docs.atlasmesh.ae/runbooks/compliance-violation"
