apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlasmesh

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- rbac.yaml
- network-policy.yaml

commonLabels:
  app: vehicle-agent
  component: vehicle-agent
  version: v1.0.0

images:
- name: atlasmesh/vehicle-agent
  newTag: latest

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vehicle-agent
  spec:
    template:
      spec:
        containers:
        - name: vehicle-agent
          env:
          - name: ENVIRONMENT
            value: "production"
          - name: LOG_LEVEL
            value: "info"
