apiVersion: v1
kind: ServiceAccount
metadata:
  name: vehicle-agent
  namespace: atlasmesh
  labels:
    app: vehicle-agent
    component: vehicle-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vehicle-agent
  namespace: atlasmesh
  labels:
    app: vehicle-agent
    component: vehicle-agent
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vehicle-agent
  namespace: atlasmesh
  labels:
    app: vehicle-agent
    component: vehicle-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vehicle-agent
subjects:
- kind: ServiceAccount
  name: vehicle-agent
  namespace: atlasmesh
