# AtlasMesh Fleet OS - Accessibility & UX Configuration
# WCAG 2.2 AA compliance and UX metrics configuration

# URLs to test for accessibility and UX compliance
urls:
  - name: "Dashboard"
    url: "http://localhost:3000"
    critical: true
    description: "Main fleet operations dashboard"
    
  - name: "Fleet View"
    url: "http://localhost:3000/fleet"
    critical: true
    description: "Real-time fleet status and vehicle monitoring"
    
  - name: "Trip Management"
    url: "http://localhost:3000/trips"
    critical: true
    description: "Trip creation, monitoring, and management"
    
  - name: "Vehicle Details"
    url: "http://localhost:3000/vehicles/test-vehicle-001"
    critical: true
    description: "Individual vehicle status and controls"
    
  - name: "Emergency Controls"
    url: "http://localhost:3000/emergency"
    critical: true
    description: "Emergency stop and safety controls"
    
  - name: "Settings"
    url: "http://localhost:3000/settings"
    critical: false
    description: "System configuration and preferences"
    
  - name: "Reports"
    url: "http://localhost:3000/reports"
    critical: false
    description: "Analytics and reporting interface"

# WCAG 2.2 AA Compliance Configuration
wcag:
  level: "AA"
  version: "2.2"
  tags: ["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]
  
  # Critical accessibility rules
  rules:
    color-contrast:
      enabled: true
      impact: "serious"
      description: "Ensure sufficient color contrast ratios"
      
    keyboard-navigation:
      enabled: true
      impact: "critical"
      description: "All interactive elements must be keyboard accessible"
      
    focus-management:
      enabled: true
      impact: "serious"
      description: "Focus indicators must be visible and logical"
      
    screen-reader:
      enabled: true
      impact: "critical"
      description: "Content must be accessible to screen readers"
      
    aria-labels:
      enabled: true
      impact: "serious"
      description: "Proper ARIA labels and descriptions required"
      
    form-labels:
      enabled: true
      impact: "serious"
      description: "All form inputs must have associated labels"
      
    heading-structure:
      enabled: true
      impact: "moderate"
      description: "Logical heading hierarchy required"
      
    link-purpose:
      enabled: true
      impact: "moderate"
      description: "Link purpose must be clear from context"
      
    image-alt:
      enabled: true
      impact: "serious"
      description: "Images must have appropriate alt text"
      
    video-captions:
      enabled: true
      impact: "serious"
      description: "Video content must have captions"

# User Experience (UX) Metrics Configuration
ux:
  # System Usability Scale (SUS) Configuration
  sus:
    enabled: true
    target_score: 75  # Industry standard for good usability
    description: "System Usability Scale measurement"
    
    # Standard SUS questions (1-5 scale)
    questions:
      - "I think that I would like to use this system frequently"
      - "I found the system unnecessarily complex"
      - "I thought the system was easy to use"
      - "I think that I would need the support of a technical person to be able to use this system"
      - "I found the various functions in this system were well integrated"
      - "I thought there was too much inconsistency in this system"
      - "I would imagine that most people would learn to use this system very quickly"
      - "I found the system very cumbersome to use"
      - "I felt very confident using the system"
      - "I needed to learn a lot of things before I could get going with this system"
  
  # Time to First Action (TtFA) Configuration
  ttfa:
    enabled: true
    target_ms: 3000  # 3 seconds to first meaningful action
    description: "Time to First Action measurement"
    
    # Critical actions that users should be able to perform quickly
    actions:
      - name: "view_fleet_status"
        selector: '[data-testid="fleet-status"]'
        description: "View overall fleet status"
        critical: true
        
      - name: "create_trip"
        selector: '[data-testid="create-trip-button"]'
        description: "Initiate trip creation"
        critical: true
        
      - name: "emergency_stop"
        selector: '[data-testid="emergency-stop"]'
        description: "Access emergency stop controls"
        critical: true
        
      - name: "vehicle_details"
        selector: '[data-testid="vehicle-card"]'
        description: "Access vehicle details"
        critical: true
        
      - name: "navigation_menu"
        selector: '[data-testid="nav-menu"]'
        description: "Access main navigation"
        critical: false
        
      - name: "search_function"
        selector: '[data-testid="search-input"]'
        description: "Use search functionality"
        critical: false
  
  # Performance UX Metrics
  performance:
    fcp_target_ms: 1500    # First Contentful Paint
    lcp_target_ms: 2500    # Largest Contentful Paint
    cls_target: 0.1        # Cumulative Layout Shift
    fid_target_ms: 100     # First Input Delay
    tti_target_ms: 3500    # Time to Interactive
    
    description: "Core Web Vitals and performance metrics"

# Validation Thresholds
thresholds:
  # Lighthouse scores (0-100)
  accessibility_score: 95      # Minimum accessibility score
  performance_score: 90        # Minimum performance score
  best_practices_score: 90     # Minimum best practices score
  seo_score: 80               # Minimum SEO score
  
  # Maximum allowed violations by severity
  max_violations:
    critical: 0    # Zero critical violations allowed
    serious: 2     # Maximum 2 serious violations
    moderate: 5    # Maximum 5 moderate violations
    minor: 10      # Maximum 10 minor violations
  
  # UX thresholds
  min_sus_score: 75           # Minimum SUS score
  max_ttfa_ms: 3000          # Maximum time to first action
  min_task_completion: 95     # Minimum task completion rate (%)

# Environment-specific configurations
environments:
  development:
    base_url: "http://localhost:3000"
    timeout_ms: 30000
    retries: 3
    
  staging:
    base_url: "https://staging.atlasmesh.com"
    timeout_ms: 45000
    retries: 2
    
  production:
    base_url: "https://app.atlasmesh.com"
    timeout_ms: 60000
    retries: 1

# Sector-specific accessibility requirements
sectors:
  defense:
    additional_requirements:
      - "508 Compliance (Section 508 of the Rehabilitation Act)"
      - "High contrast mode support"
      - "Voice navigation compatibility"
      - "Tactical display accessibility"
    
  mining:
    additional_requirements:
      - "Industrial environment visibility"
      - "Glove-friendly touch targets"
      - "Dust/dirt resistant interface elements"
    
  logistics:
    additional_requirements:
      - "Multi-language support"
      - "Warehouse lighting compatibility"
      - "Mobile device optimization"
    
  ridehail:
    additional_requirements:
      - "Driver accessibility features"
      - "Passenger information accessibility"
      - "Multi-modal interaction support"

# Reporting Configuration
reporting:
  formats: ["json", "html", "junit"]
  
  # Report retention
  retention_days: 90
  
  # Notification settings
  notifications:
    slack:
      enabled: true
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#accessibility-alerts"
      
    email:
      enabled: false
      recipients: []
      
  # Integration settings
  integrations:
    jira:
      enabled: false
      project_key: "ATLAS"
      issue_type: "Bug"
      
    github:
      enabled: true
      create_issues: true
      labels: ["accessibility", "ux", "bug"]

# Advanced Configuration
advanced:
  # Browser settings
  browser:
    headless: true
    viewport_sizes:
      - { name: "mobile", width: 375, height: 667 }
      - { name: "tablet", width: 768, height: 1024 }
      - { name: "desktop", width: 1920, height: 1080 }
      - { name: "large_desktop", width: 2560, height: 1440 }
    
  # Accessibility testing settings
  axe_core:
    version: "latest"
    locale: "en"
    
    # Custom rules
    custom_rules:
      - name: "atlasmesh-emergency-controls"
        description: "Emergency controls must be highly accessible"
        selector: '[data-testid*="emergency"]'
        requirements:
          - "keyboard_accessible"
          - "high_contrast"
          - "large_touch_target"
          
      - name: "atlasmesh-critical-actions"
        description: "Critical fleet actions must meet enhanced accessibility"
        selector: '[data-critical="true"]'
        requirements:
          - "aria_labeled"
          - "keyboard_accessible"
          - "focus_visible"
  
  # Performance monitoring
  monitoring:
    enabled: true
    baseline_comparison: true
    regression_threshold: 10  # % degradation threshold
    
  # A/B testing integration
  ab_testing:
    enabled: true
    variants: ["control", "enhanced_accessibility"]
    
# Compliance Certifications
compliance:
  certifications:
    - name: "WCAG 2.2 AA"
      required: true
      validation_frequency: "every_release"
      
    - name: "Section 508"
      required: true  # For defense sector
      validation_frequency: "quarterly"
      
    - name: "EN 301 549"
      required: false  # European accessibility standard
      validation_frequency: "annually"
      
  audit_trail:
    enabled: true
    retention_years: 7
    cryptographic_signing: true
