# SAP EWM Adapter Configuration Example
# Copy this file to sap-ewm.yaml and update with your values

# Logging configuration
log_level: "info"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

# Database configuration
database:
  host: "localhost"
  port: 5432
  user: "atlasmesh"
  password: "atlasmesh123"
  dbname: "atlasmesh_ewm"
  sslmode: "disable"

# Metrics configuration
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  interval: "15s"

# SAP EWM configuration
sap_ewm:
  host: "localhost"
  port: 8000
  client: "100"
  user: "admin"
  password: "admin123"
  auth_type: "basic"
  ssl_enabled: false
  ssl_verify: false
  api_version: "v1"
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"
  poll_interval: "5s"
  batch_size: 100
  queue_size: 1000
  warehouse:
    warehouse_id: "WH001"
    zones:
      - zone_id: "ZONE_A"
        coordinates:
          x_min: 0.0
          x_max: 100.0
          y_min: 0.0
          y_max: 100.0
      - zone_id: "ZONE_B"
        coordinates:
          x_min: 100.0
          x_max: 200.0
          y_min: 0.0
          y_max: 100.0

# Task management configuration
task:
  enabled: true
  poll_interval: "5s"
  batch_size: 100
  retry_attempts: 3
  retry_delay: "5s"
  timeout: "30s"

# Inventory management configuration
inventory:
  enabled: true
  poll_interval: "10s"
  batch_size: 50
  retry_attempts: 3
  retry_delay: "5s"
  timeout: "30s"

# Resource management configuration
resource:
  enabled: true
  poll_interval: "15s"
  batch_size: 25
  retry_attempts: 3
  retry_delay: "5s"
  timeout: "30s"
