sector: logistics
services:
  fleet-manager:
    fleet_manager:
      max_fleet_size: 50
      vehicle_types:
        - "forklift"
        - "tugger"
        - "pallet_truck"
        - "reach_truck"
      battery_management:
        enabled: true
        min_soc_for_task: 20
        max_charge_time_hours: 4
        charging_strategy: "opportunistic"
        battery_health_check: true
        parameters:
          charge_threshold: 0.8
          discharge_threshold: 0.2
      shift_scheduling:
        enabled: true
        shift_duration_hours: 8
        break_time_minutes: 30
        max_consecutive_shifts: 3
        parameters:
          shift_overlap_minutes: 15
      charging_stations:
        enabled: true
        station_count: 10
        charging_power_kw: 22
        queue_management: true
        parameters:
          max_queue_time_minutes: 30
      environmental:
        enabled: true
        max_temp_c: 45
        min_visibility_m: 5
        max_wind_speed_mps: 10
        sandstorm_detection: false
        parameters:
          humidity_threshold: 0.8
      parameters:
        warehouse_zones: ["A", "B", "C", "D"]
        max_vehicle_speed: 3.0
        precision_required: "high"
        indoor_navigation: true
  dispatch:
    dispatch:
      max_concurrent_tasks: 100
      task_prioritization:
        enabled: true
        priority_levels: 5
        emergency_override: true
        parameters:
          urgent_threshold: 0.9
      route_optimization:
        enabled: true
        algorithm: "dijkstra"
        consider_traffic: false
        consider_weather: false
        parameters:
          optimization_timeout_seconds: 30
      load_balancing:
        enabled: true
        strategy: "round_robin"
        max_load_per_vehicle: 5
        parameters:
          load_threshold: 0.8
      parameters:
        task_timeout_minutes: 30
        retry_attempts: 3
  analytics:
    analytics:
      enabled: true
      metrics_collection:
        enabled: true
        collection_interval_seconds: 60
        retention_days: 90
        parameters:
          batch_size: 1000
      reporting:
        enabled: true
        report_types: ["performance", "utilization", "efficiency"]
        schedule_interval_hours: 24
        parameters:
          report_format: "pdf"
      parameters:
        kpi_thresholds:
          utilization: 0.8
          efficiency: 0.85
  energy:
    energy:
      enabled: true
      smart_charging:
        enabled: true
        load_balancing: true
        time_of_use_pricing: false
        parameters:
          peak_hours: [9, 10, 11, 14, 15, 16]
      v2g:
        enabled: false
        grid_stabilization: false
        peak_shaving: false
        parameters:
          grid_frequency_threshold: 49.5
      energy_aware_routing:
        enabled: true
        consider_battery_soc: true
        charging_stops: true
        parameters:
          min_soc_for_route: 0.3
      parameters:
        energy_efficiency_target: 0.9
  safety:
    safety:
      enabled: true
      emergency_stop:
        enabled: true
        response_time_ms: 100
        override_capability: true
        parameters:
          stop_distance_meters: 1.0
      collision_avoidance:
        enabled: true
        min_safe_distance_meters: 1.0
        prediction_horizon_seconds: 5
        parameters:
          detection_range_meters: 10.0
      geofencing:
        enabled: true
        restricted_zones: ["maintenance", "loading_dock"]
        speed_limits: true
        parameters:
          speed_limit_mps: 2.0
      parameters:
        safety_margin_meters: 0.5
