sector: mining
services:
  fleet-manager:
    fleet_manager:
      max_fleet_size: 100
      vehicle_types:
        - "haul_truck"
        - "bulldozer"
        - "excavator"
        - "loader"
        - "drill_rig"
      battery_management:
        enabled: false
        min_soc_for_task: 0
        max_charge_time_hours: 0
        charging_strategy: "none"
        battery_health_check: false
        parameters:
          fuel_based: true
      shift_scheduling:
        enabled: true
        shift_duration_hours: 12
        break_time_minutes: 60
        max_consecutive_shifts: 2
        parameters:
          shift_handover_minutes: 30
      environmental:
        enabled: true
        max_temp_c: 50
        min_visibility_m: 15
        max_wind_speed_mps: 15
        sandstorm_detection: true
        parameters:
          dust_monitoring: true
          blast_zone_detection: true
      parameters:
        operational_zones: ["pit", "haul_road", "dump_site", "maintenance"]
        max_vehicle_speed: 10.0
        precision_required: "low"
        outdoor_navigation: true
        heavy_vehicle_dynamics: true
  dispatch:
    dispatch:
      max_concurrent_tasks: 200
      task_prioritization:
        enabled: true
        priority_levels: 3
        emergency_override: true
        parameters:
          production_priority: true
      route_optimization:
        enabled: true
        algorithm: "genetic"
        consider_traffic: true
        consider_weather: true
        parameters:
          haul_cycle_optimization: true
          truck_shovel_matching: true
      load_balancing:
        enabled: true
        strategy: "production_optimized"
        max_load_per_vehicle: 10
        parameters:
          ore_waste_balancing: true
      parameters:
        task_timeout_minutes: 120
        retry_attempts: 2
        production_targets: true
  analytics:
    analytics:
      enabled: true
      metrics_collection:
        enabled: true
        collection_interval_seconds: 300
        retention_days: 180
        parameters:
          production_metrics: true
          equipment_health: true
      reporting:
        enabled: true
        report_types: ["production", "efficiency", "maintenance", "safety"]
        schedule_interval_hours: 8
        parameters:
          shift_reports: true
      parameters:
        kpi_thresholds:
          production_target: 0.9
          equipment_utilization: 0.85
          fuel_efficiency: 0.8
  energy:
    energy:
      enabled: true
      smart_charging:
        enabled: false
        load_balancing: false
        time_of_use_pricing: false
        parameters:
          fuel_optimization: true
      v2g:
        enabled: false
        grid_stabilization: false
        peak_shaving: false
        parameters:
          power_generation: true
      energy_aware_routing:
        enabled: true
        consider_battery_soc: false
        charging_stops: false
        parameters:
          fuel_efficient_routing: true
          grade_consideration: true
      parameters:
        energy_efficiency_target: 0.7
        fuel_consumption_tracking: true
  safety:
    safety:
      enabled: true
      emergency_stop:
        enabled: true
        response_time_ms: 200
        override_capability: true
        parameters:
          stop_distance_meters: 5.0
          operator_override: true
      collision_avoidance:
        enabled: true
        min_safe_distance_meters: 5.0
        prediction_horizon_seconds: 15
        parameters:
          detection_range_meters: 100.0
          large_vehicle_detection: true
      geofencing:
        enabled: true
        restricted_zones: ["blast_zones", "maintenance_areas"]
        speed_limits: true
        parameters:
          speed_limit_mps: 8.0
          zone_specific_limits: true
      parameters:
        safety_margin_meters: 2.0
        blast_zone_safety: true
