sector: ride_hail
services:
  fleet-manager:
    fleet_manager:
      max_fleet_size: 200
      vehicle_types:
        - "robotaxi"
        - "autonomous_shuttle"
        - "ride_share_vehicle"
        - "passenger_vehicle"
      battery_management:
        enabled: true
        min_soc_for_task: 30
        max_charge_time_hours: 2
        charging_strategy: "opportunistic"
        battery_health_check: true
        parameters:
          charge_threshold: 0.8
          discharge_threshold: 0.3
      shift_scheduling:
        enabled: true
        shift_duration_hours: 12
        break_time_minutes: 60
        max_consecutive_shifts: 2
        parameters:
          shift_overlap_minutes: 30
      charging_stations:
        enabled: true
        station_count: 50
        charging_power_kw: 150
        queue_management: true
        parameters:
          max_queue_time_minutes: 15
      environmental:
        enabled: true
        max_temp_c: 50
        min_visibility_m: 20
        max_wind_speed_mps: 20
        sandstorm_detection: true
        parameters:
          passenger_comfort: true
          weather_restrictions: true
      parameters:
        urban_zones: ["downtown", "airport", "residential", "commercial"]
        max_vehicle_speed: 15.0
        precision_required: "high"
        passenger_safety: true
  dispatch:
    dispatch:
      max_concurrent_tasks: 500
      task_prioritization:
        enabled: true
        priority_levels: 3
        emergency_override: true
        dynamic_pricing: true
        parameters:
          surge_pricing: true
          passenger_priority: true
      route_optimization:
        enabled: true
        algorithm: "dijkstra"
        consider_traffic: true
        consider_weather: true
        parameters:
          optimization_timeout_seconds: 10
      load_balancing:
        enabled: true
        strategy: "demand_based"
        max_load_per_vehicle: 1
        parameters:
          passenger_capacity: true
      parameters:
        task_timeout_minutes: 15
        retry_attempts: 2
  analytics:
    analytics:
      enabled: true
      metrics_collection:
        enabled: true
        collection_interval_seconds: 30
        retention_days: 365
        parameters:
          batch_size: 5000
      reporting:
        enabled: true
        report_types: ["performance", "utilization", "efficiency", "safety", "customer_satisfaction"]
        schedule_interval_hours: 24
        parameters:
          report_format: "dashboard"
      parameters:
        kpi_thresholds:
          utilization: 0.7
          efficiency: 0.8
          customer_satisfaction: 4.5
  energy:
    energy:
      enabled: true
      smart_charging:
        enabled: true
        load_balancing: true
        time_of_use_pricing: true
        parameters:
          peak_hours: [7, 8, 9, 17, 18, 19]
      v2g:
        enabled: true
        grid_stabilization: true
        peak_shaving: true
        parameters:
          grid_frequency_threshold: 49.5
      energy_aware_routing:
        enabled: true
        consider_battery_soc: true
        charging_stops: true
        parameters:
          min_soc_for_route: 0.4
      parameters:
        energy_efficiency_target: 0.85
  safety:
    safety:
      enabled: true
      emergency_stop:
        enabled: true
        response_time_ms: 50
        override_capability: true
        parameters:
          stop_distance_meters: 2.0
      collision_avoidance:
        enabled: true
        min_safe_distance_meters: 2.0
        prediction_horizon_seconds: 3
        parameters:
          detection_range_meters: 50.0
      geofencing:
        enabled: true
        restricted_zones: ["highway", "construction", "emergency"]
        speed_limits: true
        parameters:
          speed_limit_mps: 15.0
      parameters:
        safety_margin_meters: 1.0