apiVersion: v1
kind: Namespace
metadata:
  name: atlasmesh-defense
  labels:
    sector: defense
    environment: production
    security-level: classified
    app.kubernetes.io/name: atlasmesh-fleet-os
    app.kubernetes.io/component: defense-sector
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: defense-quota
  namespace: atlasmesh-defense
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    services: "30"
    secrets: "20"
    configmaps: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defense-limits
  namespace: atlasmesh-defense
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "200m"
      memory: 512Mi
    type: Container

