# Base Service Configuration
# This file contains base configurations that are common across all sectors
# These configurations can be overridden by sector-specific configurations

sector: core
description: "Base service configuration for AtlasMesh Fleet OS"

# Common service configurations
services:
  vehicle_agent:
    # Base perception configuration
    perception:
      sensor_fusion: true
      object_detection: true
      obstacle_avoidance: true
      update_frequency_hz: 10
      sensor_config:
        lidar:
          enabled: true
          range_meters: 50
          resolution_degrees: 0.5
        camera:
          enabled: true
          resolution: "1920x1080"
          fps: 30
        radar:
          enabled: true
          range_meters: 100
    # Base localization configuration
    localization:
      gps_enabled: true
      precision_meters: 1.0
      update_frequency_hz: 5
      mapping: true
    # Base control configuration
    control:
      emergency_stop: true
      emergency_stop_distance_meters: 2.0
      max_acceleration: 2.0
      max_deceleration: 4.0
    # Base safety configuration
    safety:
      collision_avoidance: true
      safety_margin_meters: 1.0
      emergency_override: true

  fleet_manager:
    # Base fleet management configuration
    max_fleet_size: 100
    vehicle_types: ["autonomous_vehicle"]
    health_monitoring:
      enabled: true
      check_interval_seconds: 30
    status_tracking:
      enabled: true
      update_frequency_seconds: 10
    # Base battery management
    battery_management:
      enabled: true
      min_soc_for_task: 20
      charging_strategy: "opportunistic"
      health_check: true
    # Base environmental monitoring
    environmental:
      enabled: true
      max_temp_c: 50
      min_visibility_m: 10
      weather_monitoring: true

  dispatch_service:
    # Base dispatch configuration
    max_concurrent_tasks: 100
    task_timeout_minutes: 30
    retry_attempts: 3
    # Base task prioritization
    task_prioritization:
      enabled: true
      priority_levels: 5
      emergency_override: true
    # Base load balancing
    load_balancing:
      enabled: true
      strategy: "round_robin"
      max_load_per_vehicle: 5
    # Base queue management
    queue_management:
      enabled: true
      max_queue_size: 1000
      queue_timeout_minutes: 30
    # Base routing
    routing:
      algorithm: "dijkstra"
      consider_traffic: true
      consider_weather: true
      real_time_updates: true
    # Base optimization
    optimization:
      algorithm: "genetic"
      optimization_goals: ["minimize_distance", "maximize_utilization"]
      max_optimization_time_seconds: 60

  control_center_ui:
    # Base dashboard configuration
    dashboard:
      layout:
        grid_size: 12
        max_columns: 4
        max_rows: 6
        responsive: true
        mobile_optimized: false
      # Base widgets
      widgets:
        fleet_overview:
          enabled: true
          size: "large"
          refresh_interval_seconds: 30
        vehicle_status:
          enabled: true
          size: "medium"
          refresh_interval_seconds: 10
        task_queue:
          enabled: true
          size: "large"
          refresh_interval_seconds: 15
        performance:
          enabled: true
          size: "medium"
          refresh_interval_seconds: 60
        alerts:
          enabled: true
          size: "small"
          refresh_interval_seconds: 5
        maps:
          enabled: true
          size: "large"
          refresh_interval_seconds: 5
        analytics:
          enabled: true
          size: "medium"
          refresh_interval_seconds: 300
      # Base real-time updates
      real_time_updates:
        enabled: true
        update_interval_seconds: 10
        websocket_url: "ws://localhost:8080/ws"
        auto_reconnect: true
      # Base themes
      themes:
        default_theme: "default"
        available_themes: ["default", "dark", "light"]
        dark_mode: false

# Common parameters
parameters:
  # Base operational parameters
  precision_required: "medium"
  max_vehicle_speed: 10.0
  safety_margin_meters: 1.0
  real_time_tracking: true
  health_monitoring: true
  status_reporting: true
  # Base security parameters
  encryption_enabled: true
  authentication_required: true
  audit_logging: true
  # Base performance parameters
  response_timeout_seconds: 30
  retry_attempts: 3
  circuit_breaker_enabled: true
  # Base monitoring parameters
  metrics_enabled: true
  logging_level: "info"
  tracing_enabled: true
