# Logistics Service Configuration
# This file contains logistics-specific service configurations
# that override base configurations for warehouse and port operations

sector: logistics
description: "Logistics service configuration for warehouse and port automation"

# Logistics-specific service configurations
services:
  vehicle_agent:
    # Logistics-specific perception
    perception:
      indoor_navigation: true
      pallet_detection: true
      precision_required: "high"
      max_speed_mps: 3.0
      sensor_config:
        lidar:
          range_meters: 10
          resolution_degrees: 0.5
        camera:
          resolution: "1920x1080"
          fps: 30
        radar:
          enabled: false
    # Logistics-specific localization
    localization:
      gps_denied: true
      indoor_mapping: true
      precision_meters: 0.1
      update_frequency_hz: 10
    # Logistics-specific control
    control:
      low_speed_control: true
      precision_steering: true
      emergency_stop_distance_meters: 1.0
    # Logistics-specific safety
    safety:
      indoor_safety: true
      pedestrian_detection: true
      safety_margin_meters: 0.5

  fleet_manager:
    # Logistics-specific fleet management
    max_fleet_size: 50
    vehicle_types: ["forklift", "tugger", "pallet_truck", "reach_truck"]
    battery_management:
      min_soc_for_task: 20
      charging_strategy: "opportunistic"
    shift_scheduling:
      enabled: true
      shift_duration_hours: 8
      break_time_minutes: 30
    charging_stations:
      enabled: true
      station_count: 10
      charging_power_kw: 22
    environmental:
      max_temp_c: 45
      min_visibility_m: 5
      sandstorm_detection: false

  dispatch_service:
    # Logistics-specific dispatch
    max_concurrent_tasks: 100
    task_prioritization:
      priority_levels: 5
      emergency_override: true
    load_balancing:
      strategy: "round_robin"
      max_load_per_vehicle: 5
    queue_management:
      max_queue_size: 1000
      queue_timeout_minutes: 30
    routing:
      algorithm: "dijkstra"
      consider_traffic: false
      consider_weather: false
      multi_stop_routing:
        enabled: true
        max_stops_per_route: 10
    optimization:
      algorithm: "genetic"
      optimization_goals: ["minimize_distance", "maximize_utilization", "minimize_time"]

  control_center_ui:
    # Logistics-specific dashboard
    dashboard:
      layout:
        mobile_optimized: true
        warehouse_layout: true
      widgets:
        fleet_overview:
          refresh_interval_seconds: 30
          show_battery_status: true
          show_task_progress: true
        vehicle_status:
          refresh_interval_seconds: 10
          show_location: true
          show_speed: true
        task_queue:
          refresh_interval_seconds: 15
          show_priority: true
          show_estimated_time: true
        performance:
          refresh_interval_seconds: 60
          show_efficiency: true
          show_utilization: true
        alerts:
          refresh_interval_seconds: 5
          show_critical_only: false
        maps:
          refresh_interval_seconds: 5
          show_warehouse_zones: true
          show_vehicle_paths: true
        analytics:
          refresh_interval_seconds: 300
          show_trends: true
          show_kpis: true
      real_time_updates:
        update_interval_seconds: 5
        warehouse_events: true
      themes:
        default_theme: "logistics"
        available_themes: ["logistics", "dark", "light"]
        color_scheme: "blue_green"

# Logistics-specific parameters
parameters:
  warehouse_zones: ["A", "B", "C", "D"]
  indoor_operations: true
  precision_required: "high"
  max_vehicle_speed: 3.0
  safety_margin_meters: 0.5
  battery_management: true
  shift_based_operations: true
  warehouse_automation: true
  indoor_navigation: true
  pallet_handling: true
