apiVersion: v1
kind: Namespace
metadata:
  name: atlasmesh-ride-hail
  labels:
    sector: ride_hail
    environment: production
    app.kubernetes.io/name: atlasmesh-fleet-os
    app.kubernetes.io/component: ride-hail-sector
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ride-hail-quota
  namespace: atlasmesh-ride-hail
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "50"
    services: "60"
    secrets: "20"
    configmaps: "40"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ride-hail-limits
  namespace: atlasmesh-ride-hail
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: "100m"
      memory: 256Mi
    type: Container

