# AtlasMesh Fleet OS - Development Environment Values

# Override global settings for development
global:
  imageRegistry: "localhost:5000"
  imagePullSecrets: []
  storageClass: "standard"

environment: "development"
region: "local"

# Reduced resource requirements for development
services:
  apiGateway:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    autoscaling:
      enabled: false
  
  fleetManager:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    autoscaling:
      enabled: false
  
  vehicleGateway:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    autoscaling:
      enabled: false
  
  policyEngine:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  
  weatherFusion:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  
  telemetryIngest:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    autoscaling:
      enabled: false

# UI with reduced resources
ui:
  controlCenter:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  
  mobileApp:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Lightweight database configuration
postgresql:
  primary:
    persistence:
      size: 10Gi
      storageClass: "standard"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
  readReplicas:
    replicaCount: 0  # No read replicas in dev

# Lightweight Redis
redis:
  master:
    persistence:
      size: 1Gi
      storageClass: "standard"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  replica:
    replicaCount: 0  # No replicas in dev

# Lightweight Kafka
kafka:
  replicaCount: 1
  persistence:
    size: 5Gi
    storageClass: "standard"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  zookeeper:
    replicaCount: 1
    persistence:
      size: 1Gi

# Monitoring with reduced resources
monitoring:
  prometheus:
    server:
      persistentVolume:
        size: 5Gi
        storageClass: "standard"
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
    alertmanager:
      persistentVolume:
        size: 1Gi
  
  grafana:
    persistence:
      size: 1Gi
      storageClass: "standard"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  
  jaeger:
    elasticsearch:
      replicas: 1

# Ingress for local development
ingress:
  hosts:
    - host: api.fleet-os.local
      paths:
        - path: /
          pathType: Prefix
          service: api-gateway
    - host: fleet.fleet-os.local
      paths:
        - path: /
          pathType: Prefix
          service: control-center
  tls: []  # No TLS in development

# Disable backup in development
backup:
  enabled: false

# Development feature flags
featureFlags:
  autonomousDispatch: true
  predictiveMaintenance: false  # Disabled in dev to reduce load
  weatherIntegration: true
  arabicLocalization: false     # Disabled in dev
  uaeGovernmentIntegration: false  # Disabled in dev

# Reduced resource quotas
resourceQuotas:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    persistentvolumeclaims: "20"

# Relaxed security for development
security:
  networkPolicies:
    enabled: false
  podSecurityPolicy:
    enabled: false
