# AtlasMesh Fleet OS - Staging Environment Values

environment: "staging"
region: "uae-central"

# Staging-specific image configuration
image:
  tag: "staging-latest"

# Moderate resource allocation for staging
services:
  apiGateway:
    replicas: 2
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
  
  fleetManager:
    replicas: 2
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
  
  vehicleGateway:
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 8
  
  policyEngine:
    replicas: 2
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
  
  weatherFusion:
    replicas: 2
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
  
  telemetryIngest:
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 8

# UI configuration for staging
ui:
  controlCenter:
    replicas: 2
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 500m
        memory: 1Gi
  
  mobileApp:
    replicas: 1
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Database configuration for staging
postgresql:
  primary:
    persistence:
      size: 50Gi
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 8Gi
  readReplicas:
    replicaCount: 1
    persistence:
      size: 50Gi

# Redis configuration for staging
redis:
  master:
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
  replica:
    replicaCount: 1
    persistence:
      size: 10Gi

# Kafka configuration for staging
kafka:
  replicaCount: 3
  persistence:
    size: 25Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  zookeeper:
    replicaCount: 3
    persistence:
      size: 5Gi

# Monitoring for staging
monitoring:
  prometheus:
    server:
      persistentVolume:
        size: 25Gi
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi
    alertmanager:
      persistentVolume:
        size: 5Gi
  
  grafana:
    persistence:
      size: 5Gi
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 500m
        memory: 1Gi
  
  jaeger:
    elasticsearch:
      replicas: 2

# Staging ingress configuration
ingress:
  hosts:
    - host: api-staging.atlasmesh.ae
      paths:
        - path: /
          pathType: Prefix
          service: api-gateway
    - host: fleet-staging.atlasmesh.ae
      paths:
        - path: /
          pathType: Prefix
          service: control-center
  tls:
    - secretName: atlasmesh-staging-tls
      hosts:
        - api-staging.atlasmesh.ae
        - fleet-staging.atlasmesh.ae

# Backup configuration for staging
backup:
  enabled: true
  schedule: "0 3 * * *"  # Daily at 3 AM
  retention: "14d"       # 2 weeks retention

# Feature flags for staging (all enabled for testing)
featureFlags:
  autonomousDispatch: true
  predictiveMaintenance: true
  weatherIntegration: true
  arabicLocalization: true
  uaeGovernmentIntegration: true

# Resource quotas for staging
resourceQuotas:
  hard:
    requests.cpu: "30"
    requests.memory: "60Gi"
    limits.cpu: "60"
    limits.memory: "120Gi"
    persistentvolumeclaims: "30"

# Security configuration for staging
security:
  rbac:
    enabled: true
  networkPolicies:
    enabled: true
  podSecurityPolicy:
    enabled: true

# Staging-specific environment variables
env:
  - name: ENVIRONMENT
    value: "staging"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: ENABLE_PROFILING
    value: "true"
  - name: MOCK_EXTERNAL_SERVICES
    value: "true"
